### ISSUE TITLE
Access to Dashboard not wirking

### ISSUE THREAD

**Issue by Otti24xx** [storj-thirdparty/qnap-storagenode-app#11]
Access to http://192.168.177.57:14002/ is not working - Server has started

**Comment by kmozurkewich** [comment]
Hi @Otti24xx - that happens when the node doesn't have an identity created.  Can you share the log file output and confirm your identity is successfully created?

**Comment by Otti24xx** [comment]
Thx for your help, the folder '\Public\identity\logs' is emty but in the app it shows 

Storj Status
Container named storjlabsSnContainer launched

and in the app by Identity it shows: 'Identity files exist.'

**Comment by Otti24xx** [comment]
in the app on the last line it shows:

LATEST LOG :

acc6e25a0d27 storjlabs/storagenode:latest "/entrypoint" 1 second ago Up Less than a second 192.168.177.57:14002->14002/tcp, 0.0.0.0:28967->28967/tcp storjlabsSnContainer

**Comment by paragpadsumbiya** [comment]
Hello @Otti24xx 

I have checked things in details and its working in all normal conditions as storj dashboard is working. I think may be some issues specifically your setup or server . So to check that in details can you please provide your details in personal so we can check for you for the same. You can contact me on my email paragpadsumbiya@gmail.com. Let me know if there anything else.

**Comment by kmozurkewich** [comment]
@Otti24xx  - can you also share with @paragpadsumbiya the contents of /var/log/STORJ ?

**Comment by Otti24xx** [comment]
how can I find the logs on my QNAP TS-231P2

**Comment by Otti24xx** [comment]
@paragpadsumbiya - I wrote you a email, thx for your help

**Comment by Otti24xx** [comment]
in the newest version the fields are not emty, all are filled with data after installation of the app

**Comment by kmozurkewich** [comment]
@Otti24xx - is the container starting up for you?

**Comment by Otti24xx** [comment]
the cointainer is stopped and i can not start it:

1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
        github.com/spf13/cobra.(*Command).ExecuteC:945                                                                                         
        github.com/spf13/cobra.(*Command).Execute:885                                                                                          
        storj.io/private/process.ExecWithCustomConfig:88                                                                                       
        storj.io/private/process.ExecCustomDebug:70                                                                                            
        main.main:323                                                                                                                          
        runtime.main:203

**Comment by Otti24xx** [comment]
![image](https://user-images.githubusercontent.com/47483607/90093628-51dda080-dd2c-11ea-8e1a-d42bf58d1a65.png)

When I set it of autostart I get a error (Error Code 500: unexpected repository name)

**Comment by Otti24xx** [comment]
with version 1.09 the same problem - my logfiles are and server stopped after start and restart:

1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabase:272                                                                        
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabases:187                                                                       
        storj.io/storj/storagenode/storagenodedb.New:174                                                                                       
        main.cmdRun:150                                                                                                                        
        storj.io/private/process.cleanup.func1.4:353                                                                                           
        storj.io/private/process.cleanup.func1:371                                                                                             
        github.com/spf13/cobra.(*Command).execute:840                                                                                          
        github.com/spf13/cobra.(*Command).ExecuteC:945                                                                                         
        github.com/spf13/cobra.(*Command).Execute:885                                                                                          
        storj.io/private/process.ExecWithCustomConfig:88                                                                                       
        storj.io/private/process.ExecCustomDebug:70                                                                                            
        main.main:323                                                                                                                          
        runtime.main:203

**Comment by Otti24xx** [comment]
in Logs i have found the error:

Error: Error starting master database on storagenode: storage node database error: unable to open database file: operation not permitted

**Comment by Otti24xx** [comment]
2020-08-13T08:19:28.667Z        INFO    Configuration loaded    {"Location": "/app/config/config.yaml"}                                                                                                                                                                                         
2020-08-13T08:19:28.672Z        INFO    Operator email  {"Address": "TGB-Ott@online.de"}                                                                                                                                                                                                        
2020-08-13T08:19:28.672Z        INFO    Operator wallet {"Address": "0x80080d781b7AC48Cce5b1D8E6360b0316E4EAcE3"}                                                                                                                                                                               
Error: Error starting master database on storagenode: storage node database error: unable to open database file: operation not permitted                                                                                                                                                        
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabase:272                                                                                                                                                                                                                         
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabases:187                                                                                                                                                                                                                        
        storj.io/storj/storagenode/storagenodedb.New:174                                                                                                                                                                                                                                        
        main.cmdRun:150                                                                                                                                                                                                                                                                         
        storj.io/private/process.cleanup.func1.4:353                                                                                                                                                                                                                                            
        storj.io/private/process.cleanup.func1:371                                                                                                                                                                                                                                              
        github.com/spf13/cobra.(*Command).execute:840                                                                                                                                                                                                                                           
        github.com/spf13/cobra.(*Command).ExecuteC:945                                                                                                                                                                                                                                          
        github.com/spf13/cobra.(*Command).Execute:885                                                                                                                                                                                                                                           
        storj.io/private/process.ExecWithCustomConfig:88                                                                                                                                                                                                                                        
        storj.io/private/process.ExecCustomDebug:70                                                                                                                                                                                                                                             
        main.main:323                                                                                                                                                                                                                                                                           
        runtime.main:203

**Comment by paragpadsumbiya** [comment]
Hello @Otti24xx 

I have checked your email and found that you have everything is running fine before as your container is launched.

But you doen't have your port open 1402 so you were not able to access dashboard.

So can you please confirm Is it not open on the qnap or on your home router ?

**Comment by kmozurkewich** [comment]
@Otti24xx  - regarding your **(Error Code 500: unexpected repository name)** error, please check this thread:
https://forum.qnap.com/viewtopic.php?t=142853

Have you done anything manually(command line, etc.) related to docker on your qnap by chance??

**Comment by Otti24xx** [comment]
@kmozurkewich - I have installed all only with the QNAP App first version 1.02 than 1.08 and now 1.09

**Comment by Otti24xx** [comment]
@paragpadsumbiya - How can I open the Port 14002 on my QNAP?

**Comment by paragpadsumbiya** [comment]
Hello @Otti24xx 

If you are tying to access dashboard from outside of internal network then this link will be helpful.
https://www.qnap.com/en/how-to/faq/article/how-do-i-set-up-port-forwarding-on-the-nas/
Otherwise we need to know how you are accessing dashboard ?

**Comment by Otti24xx** [comment]
I have all new installed and startet, same Error:

2020-08-13T18:40:07.603Z        INFO    Configuration loaded    {"Location": "/app/config/config.yaml"}                                                                                                                               
2020-08-13T18:40:07.647Z        INFO    Operator email  {"Address": "mymail"}                                                                                                                                         
2020-08-13T18:40:07.651Z        INFO    Operator wallet {"Address": "mywallet"}                                                                                                                     
Error: Error starting master database on storagenode: storage node database error: unable to open database file: operation not permitted                                                                                              
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabase:272                                                                                                                                                               
        storj.io/storj/storagenode/storagenodedb.(*DB).openDatabases:187                                                                                                                                                              
        storj.io/storj/storagenode/storagenodedb.New:174                                                                                                                                                                              
        main.cmdRun:150                                                                                                                                                                                                               
        storj.io/private/process.cleanup.func1.4:353                                                                                                                                                                                  
        storj.io/private/process.cleanup.func1:371                                                                                                                                                                                    
        github.com/spf13/cobra.(*Command).execute:840                                                                                                                                                                                 
        github.com/spf13/cobra.(*Command).ExecuteC:945                                                                                                                                                                                
        github.com/spf13/cobra.(*Command).Execute:885                                                                                                                                                                                 
        storj.io/private/process.ExecWithCustomConfig:88                                                                                                                                                                              
        storj.io/private/process.ExecCustomDebug:70                                                                                                                                                                                   
        main.main:323                                                                                                                                                                                                                 
        runtime.main:203

**Comment by Otti24xx** [comment]
Error: Error starting master database on storagenode: storage node database error: unable to open database file: operation not permitted

**Comment by Otti24xx** [comment]
Thank you, but this is not working – dashboard can not be open

 

Von: Parag Padsumbiya [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2020 17:00
An: storj-thirdparty/qnap-storagenode-app <qnap-storagenode-app@noreply.github.com>
Cc: Otti24xx <johannes.ott@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [storj-thirdparty/qnap-storagenode-app] Access to Dashboard not wirking (#11)

 

Hello @Otti24xx <https://github.com/Otti24xx> 

If you are tying to access dashboard from outside of internal network then this link will be helpful.
https://www.qnap.com/en/how-to/faq/article/how-do-i-set-up-port-forwarding-on-the-nas/
Otherwise we need to know how you are accessing dashboard ?

**Comment by paragpadsumbiya** [comment]
Hello @Otti24xx 

Please reopen this if you have still issue with Dashboard.

Thanks
Parag Padsumbiya
