### ISSUE TITLE
Container Station not available on older QNAP NAS

### ISSUE THREAD

**Issue by mikebrownie** [storj-thirdparty/qnap-storagenode-app#18]
I was unable to complete the installation because my QNAP does not support container station. This is my error after an attempted install:

```
Type	Date	Time	Users	Source IP	Computer name	Content	
Error	2021/05/02	21:20:56	System	127.0.0.1	localhost	[App Center] Failed to install Storj Storage Node 1.1.0. You must first install and enable container-station >= 1.7.2041.	
```

On the website:

>*Container Station is available from the QTS App Center (QTS 4.2 or above) for x86-based TS-x51, TS-x51+, TS-x51A, TS-x53, TS-x53A, TS/TVS-x63, TVS-x70, TVS-x71, TS/SS-x79, TS/TVS-x80 and TVS-x82 series, and the ARM-based TS-531P, TS-x31+ series with a minimum of 1GB RAM.

Could the installation be done without container station?

**Comment by kmozurkewich** [comment]
@mikebrownie - Container Station is a requirement for this app.  We have discussed a non-container version of the app but that is not available at the present time.
